### ISSUE TITLE
Srila Prabhupada Pranam Mantra needs to be complete

### ISSUE THREAD

**Issue by meets2tarun** [byciitp/byciitp.github.io#1] opened 2020-07-25 10:14 UTC
Hare Krishna, 
In temple program pdf, Prabhupada Pranam Mantra is incompete. It happened twice in the pdf

![image](https://user-images.githubusercontent.com/15213246/88454458-88db3780-ce8d-11ea-8c58-54ea5b1933b8.png)
@sheetal-g9

**Comment by sheetal-g9** [comment] 2020-07-25 15:39
The issue is resolved in this commit : 
https://github.com/byciitp/byciitp.github.io/commit/cb9c931f786ba259dc68c17c4ad1f80a92092b1a

**Closed as completed by sheetal-g9** 2020-07-25 15:39 UTC
